<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140726151952 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_oauth_domain_model_oauthtoken ADD account VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_oauth_domain_model_oauthtoken ADD CONSTRAINT FK_7E3F2BCC7D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_7E3F2BCC7D3656A4 ON famelo_oauth_domain_model_oauthtoken (account)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_oauth_domain_model_oauthtoken DROP FOREIGN KEY FK_7E3F2BCC7D3656A4");
		$this->addSql("DROP INDEX UNIQ_7E3F2BCC7D3656A4 ON famelo_oauth_domain_model_oauthtoken");
		$this->addSql("ALTER TABLE famelo_oauth_domain_model_oauthtoken DROP account");
	}
}