#%RAML 0.8

title: GitHub API
baseUri: https://api.github.com
version: v3
contentType: application/json
authorizationMethod: QUERY_STRING
headers:
  Accept: 'application/vnd.github.v3+json'

traits:
  - secured:
      responses:
        401:
          body:
            application/json:
              schema: |
                { "$schema": "http://json-schema.org/schema",
                  "type": "object",
                  "description": "Response",
                  "properties": {
                    "message":  { "type": "string" },
                    "documentation_url":  { "type": "string" }
                  }
                }


/repositories:
  name: Repository
  get:
    queryParameters:
      since:
        description: The integer ID of the last Repository that you’ve seen.

/users:
  /{username}:
    get:
      is: [secured]
      responses:
        200:
          body:
            application/json:
              schema: |
                { "$schema": "http://json-schema.org/schema",
                  "type": "object",
                  "description": "User",
                  "properties": {
                    "login":  { "type": "string" }
                  }
                }
