#%RAML 0.8

title: Harvest API
baseUri: https://api.harvestapp.com
authorizationMethod: QUERY_STRING
contentType: application/json
headers:
  'Content-Type': 'application/json'
  'Accept': 'application/json'

/clients:
  get:
    queryParameters:
      updated_since:
        description: You can filter by updated_since. To show only the clients that have been updated since "2010-09-25 18:30", pass the UTC date time value (URL encoded).
  /{clientId}:
    get:
      responses:
        200:
          body:
            application/json:
              schema: |
                { "$schema": "http://json-schema.org/schema",
                  "type": "object",
                  "description": "Client",
                  "properties": {
                    "name":  { "type": "string" },
                    "details":  { "type": "string" }
                  }
                }

/invoices:
  get:
    responses:
      200:
        body:
          application/json:
            transformation:
              type: array
              children:
                type: object
                path: invoices
                relations:
                  details:
                    requestPath: /invoices/{id}
                    arguments:
                      id:
                        path: id
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              transformation:
                type: object
                path: invoice
                relations:
                  customer:
                    requestPath: /clients/{id}
                    arguments:
                      id:
                        path: client_id

/clients:
  get:
    responses:
      200:
        body:
          application/json:
            transformation:
              type: array
              children:
                type: object
                path: clients
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              transformation:
                type: object
                path: client
                relations:
                  contacts:
                    requestPath: /clients/{id}/contacts
                    arguments:
                      id:
                        path: id
    /contacts:
      get:
        responses:
          200:
            body:
              application/json:
                transformation:
                  type: array
                  children:
                    type: object
                    path: contacts
