
Famelo:
  Oauth:
    UserAgent: Famelo.Oauth
    missingPartyHandler:
      className: \Famelo\Oauth\Security\MissingPartyHandler\AutoCreatePartyHandler
      options:
        uri: /
Neos:
  Flow:
    object:
      excludeClasses:
        'lusitanian.*':
          - '.*'
        'alecsammon.*':
          - '.*'
